### ISSUE TITLE
bower install gives error: ENORESTARGET  Tag/branch purescript-test-unit-7.0.0 does not exist

### ISSUE THREAD

**Issue by liminalisht** [eskimor/purescript-subscriber#3]
I'm actually trying to build `servant-purescript`, but traced the problem to an issue with this package that is stopping me from doing so.

`bower install purescript-subscriber --save` gives the following error:

`bower ENORESTARGET  Tag/branch purescript-test-unit-7.0.0 does not exist`

The `bower.json` file for this package includes the line 
`"purescript-signal": "git@github.com:eskimor/purescript-signal.git#purescript-test-unit-7.0.0"` pointing to a branch that doesn't exist. 

Did you mean something like this instead?

`
"purescript-signal": "git@github.com:eskimor/purescript-signal.git",
"purescript-test-unit": "^7.0.0"
`

BTW, reading through the code of `servant-purescript`, `purescript-bridge`, `servant-subscriber`, etc., it looks like you've done a bunch of fantastic work. Thank you.

**Comment by eskimor** [comment]
Sorry about that I had to use some PRs directly because upstream had not yet merged them yet - fixed now. (your error occurred, because I deleted my branch when bodil merged my changes - sorry about that.)

Thanks for the kudos! :-) 

I am happy that you are playing with subscriber, just keep in mind that purescript-subscriber currently only offers a very low-level interface that also is about to change and will get an additional more high level interface.
